version: '2'
services:
  testapp-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/testapp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testapp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
